version: '3.8'

services:
  app:
    image: polymorphisma/postwizard:latest  # Replace with the image name for your app
    build: .
    container_name: postWizard-backend
    ports:
      - "8080:8080"  # Adjust the ports as needed
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    networks:
      - postwizard-network

  db:
    image: postgres:latest  # Use an appropriate version of PostgreSQL
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data  # Persist PostgreSQL data
    restart: always
    networks:
      - postwizard-network


networks:
  postwizard-network:
    driver: bridge
