"""relationship maintend

Revision ID: e914c8e2f525
Revises: 0162302d4c94
Create Date: 2024-08-28 07:54:28.908300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e914c8e2f525'
down_revision = '0162302d4c94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('uploaded_link', sa.Text(), nullable=False))
    op.add_column('upload', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_upload_id', table_name='upload')
    op.create_foreign_key(None, 'upload', 'user', ['user_id'], ['id'])
    op.drop_index('ix_user_id', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_constraint(None, 'upload', type_='foreignkey')
    op.create_index('ix_upload_id', 'upload', ['id'], unique=False)
    op.drop_column('upload', 'user_id')
    op.drop_column('upload', 'uploaded_link')
    # ### end Alembic commands ###
