name: Docker Image CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Docker build
      run: |
        docker build . -t polymorphisma/postwizard:latest

    - name: Docker push
      run: |
        docker push polymorphisma/postwizard:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:

      - uses: actions/checkout@v3

      - name: Restart docker-compose on the VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd postWizard-backend
            docker compose down
            docker pull polymorphisma/postwizard:latest
            docker compose up -d